name: Send Email Notification
description: Send email notification on repository changes

inputs:
  email-to:
    description: 'Comma-separated list of email recipients'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r .github/workflows/modules/notification/scripts/requirements.txt
      shell: bash

    - name: Send notification
      run: python .github/workflows/modules/notification/scripts/send-alert.py "${{ inputs.email-to }}"
      shell: bash
