name: Kubernetes Security Scanning
description: Run security scans on Kubernetes manifests

outputs:
  scan-results:
    description: 'Results of security scans'
    value: ${{ steps.scan-results.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Kubescape scan
      run: ./.github/workflows/modules/scanning/scripts/kubescape-scan.sh
      shell: bash

    - name: Run Trivy scan
      run: ./.github/workflows/modules/scanning/scripts/trivy-scan.sh
      shell: bash

    - name: Set scan results output
      id: scan-results
      run: echo "results=$(cat scan-results.json)" >> $GITHUB_OUTPUT
      shell: bash
