name: Validation and Deployment Scan
description: Validate Kubernetes manifests and scan deployed resources

inputs:
  scan-results:
    description: 'Results from security scans'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run GoDaddy validation
      run: ./.github/workflows/modules/validation/scripts/godgo-validate.sh
      shell: bash

    - name: Deploy and scan
      run: ./.github/workflows/modules/validation/scripts/deploy-scan.sh
      shell: bash
