name: Kubernetes Security Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notifications:
    uses: ./.github/workflows/modules/notification/action.yml
    secrets:
      EMAIL_TO: "dedy@gmail.com,fery@gmail.com"

  security-scan:
    needs: notifications
    uses: ./.github/workflows/modules/scanning/action.yml

  validation:
    needs: security-scan
    uses: ./.github/workflows/modules/validation/action.yml
    with:
      scan-results: ${{ needs.security-scan.outputs.scan-results }}
